#!/usr/bin/env node
/*
 * Makes BurnMeter behave like a desktop app on Windows.
 *
 *   node install-desktop.js              shortcuts + start on login
 *   node install-desktop.js --no-startup shortcuts only
 *   node install-desktop.js --uninstall  remove everything this created
 *
 * What it creates:
 *   Desktop\BurnMeter.lnk            the full dashboard, in its own window
 *   Desktop\BurnMeter Gauge.lnk      just the floating gauge
 *   Start Menu\BurnMeter\*.lnk       both of the above, plus Stop
 *   Startup\BurnMeter.lnk            starts the server + gauge at login
 *
 * Each shortcut runs wscript.exe against a .vbs launcher, so there is never a
 * console window. The launchers are (re)written here with the absolute path to
 * this machine's node.exe, so they work even if node isn't on the PATH that
 * Explorer hands to shortcuts.
 */
'use strict';

const fs   = require('fs');
const os   = require('os');
const path = require('path');
const { execFileSync } = require('child_process');

const APP  = __dirname;
const DESK = path.join(APP, 'desktop');
const ICON = path.join(DESK, 'burnmeter.ico');
const args = new Set(process.argv.slice(2));
const UNDO = args.has('--uninstall');

if (process.platform !== 'win32') {
  console.error('This installer is Windows-only. See README.md for macOS (launchd) and Linux (systemd --user).');
  process.exit(1);
}

const HOME    = os.homedir();
const DESKTOP = shellFolder('Desktop')  || path.join(HOME, 'Desktop');
const STARTMENU = shellFolder('Programs') || path.join(HOME, 'AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs');
const STARTUP = shellFolder('Startup')  || path.join(STARTMENU, 'Startup');
const GROUP   = path.join(STARTMENU, 'BurnMeter');

function ps(script) {
  return execFileSync('powershell.exe',
    ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-Command', script],
    { encoding: 'utf8', windowsHide: true }).trim();
}

function shellFolder(name) {
  try { return ps(`(New-Object -ComObject WScript.Shell).SpecialFolders("${name}")`) || null; }
  catch { return null; }
}

// ------------------------------------------------------------- launchers ---

function nodePath() {
  try {
    const p = ps('(Get-Command node -ErrorAction SilentlyContinue).Source');
    if (p && fs.existsSync(p)) return p;
  } catch {}
  return process.execPath;                      // the node running this script
}

const NODE = nodePath();

const LAUNCHERS = {
  'burnmeter.vbs':   { flag: '--open',      note: 'open the dashboard' },
  'gauge.vbs':       { flag: '--open-mini', note: 'open the floating gauge' },
  'autostart.vbs':   { flag: '--open-mini', note: 'login entry point - server + gauge' },
  'server-only.vbs': { flag: '',            note: 'background server, no window' }
};

function writeLaunchers() {
  fs.mkdirSync(DESK, { recursive: true });
  for (const [file, { flag, note }] of Object.entries(LAUNCHERS)) {
    const body =
`' BurnMeter - ${note}.
' Generated by install-desktop.js. Runs hidden via wscript.exe, so no console
' window ever appears. If the server is already running this just opens the
' window and exits.
Option Explicit
Dim sh
Set sh = CreateObject("WScript.Shell")
sh.Run """${NODE}"" ""${path.join(APP, 'server.js')}""${flag ? ' ' + flag : ''}", 0, False
`;
    fs.writeFileSync(path.join(DESK, file), body, 'ascii');
  }
  // Stop helper: only kills node processes actually running this app.
  fs.writeFileSync(path.join(DESK, 'stop.ps1'),
`# Stops the BurnMeter background server (and nothing else).
$target = '${path.join(APP, 'server.js').replace(/\\/g, '\\\\')}'
$hits = Get-CimInstance Win32_Process -Filter "Name = 'node.exe'" |
        Where-Object { $_.CommandLine -like "*burnmeter*server.js*" }
if (-not $hits) { Write-Output 'BurnMeter is not running.'; exit 0 }
foreach ($p in $hits) { Stop-Process -Id $p.ProcessId -Force -ErrorAction SilentlyContinue }
Write-Output "Stopped $($hits.Count) BurnMeter process(es)."
`, 'ascii');
  fs.writeFileSync(path.join(DESK, 'stop.vbs'),
`' BurnMeter - stop the background server.
Option Explicit
Dim sh
Set sh = CreateObject("WScript.Shell")
sh.Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -File ""${path.join(DESK, 'stop.ps1')}""", 0, False
`, 'ascii');
  console.log(`- launchers written (node: ${NODE})`);
}

// ------------------------------------------------------------- shortcuts ---

function link(lnkPath, vbs, description) {
  const q = s => s.replace(/'/g, "''");
  ps(`
    $s = (New-Object -ComObject WScript.Shell).CreateShortcut('${q(lnkPath)}')
    $s.TargetPath = '${q(path.join(process.env.SystemRoot || 'C:\\Windows', 'System32', 'wscript.exe'))}'
    $s.Arguments = '"${q(path.join(DESK, vbs))}"'
    $s.WorkingDirectory = '${q(APP)}'
    $s.IconLocation = '${q(ICON)},0'
    $s.Description = '${q(description)}'
    $s.Save()
  `);
  console.log('- ' + lnkPath.replace(HOME, '~'));
}

function rm(p) {
  try { if (fs.existsSync(p)) { fs.rmSync(p, { recursive: true, force: true }); console.log('- removed ' + p.replace(HOME, '~')); } }
  catch (e) { console.error('  could not remove ' + p + ': ' + e.message); }
}

// ------------------------------------------------------------------ main ---

console.log('\nBurnMeter desktop setup\n');

if (UNDO) {
  rm(path.join(DESKTOP, 'BurnMeter.lnk'));
  rm(path.join(DESKTOP, 'BurnMeter Gauge.lnk'));
  rm(path.join(STARTUP, 'BurnMeter.lnk'));
  rm(GROUP);
  console.log('\nShortcuts removed. The app itself is still at ' + APP);
  console.log('Stop the running server with:  powershell -File "' + path.join(DESK, 'stop.ps1') + '"\n');
  process.exit(0);
}

if (!fs.existsSync(ICON)) {
  console.log('- generating icon');
  try { execFileSync(process.execPath, [path.join(APP, 'make-icon.js')], { stdio: 'ignore' }); } catch {}
}

writeLaunchers();

fs.mkdirSync(GROUP, { recursive: true });
link(path.join(DESKTOP, 'BurnMeter.lnk'),        'burnmeter.vbs', 'BurnMeter dashboard - what your Claude Code usage is worth');
link(path.join(DESKTOP, 'BurnMeter Gauge.lnk'),  'gauge.vbs',     'BurnMeter floating gauge - live burn rate');
link(path.join(GROUP,   'BurnMeter.lnk'),        'burnmeter.vbs', 'BurnMeter dashboard');
link(path.join(GROUP,   'BurnMeter Gauge.lnk'),  'gauge.vbs',     'BurnMeter floating gauge');
link(path.join(GROUP,   'Stop BurnMeter.lnk'),   'stop.vbs',      'Stop the BurnMeter background server');

if (!args.has('--no-startup')) {
  link(path.join(STARTUP, 'BurnMeter.lnk'), 'autostart.vbs', 'Start BurnMeter at login');
  console.log('\n  Starts at login, opening the floating gauge.');
  console.log('  Server only, no window? Point that shortcut at server-only.vbs,');
  console.log('  or re-run with --no-startup to skip login start entirely.');
}

console.log(`
Done. Two icons on your desktop:

  BurnMeter          the full dashboard in its own window
  BurnMeter Gauge    the small floating gauge

Both are real windows - move them, resize them, minimise them, drag them to a
second monitor. The gauge has a pin button to keep it above everything else.
`);
